
weeks = 2

men = [
    "adam",
    "chris",
    "dillan",
    "dre",
    "ethan",
    "jj",
    "joey",
    "ryan",
    "scali",
    "wes"
]

women = [
    "amber",
    "ashleigh",
    "brittany",
    "coleysia",
    "jacy",
    "jessica",
    "kayla",
    "paige",
    "shanley",
    "simone"
]

[week1]
pairs = [
    ["wes", "kayla"],
    ["ethan", "shanley"],
    ["adam", "brittany"],
    ["dre", "jacy"],
    ["jj", "simone"],
    ["chris", "jessica"],
    ["joey", "paige"],
    ["scali", "ashleigh"],
    ["ryan", "amber"],
    ["dillan", "coleysia"]
]
correct = 2
booth = ["chris", "shanley"]
booth_status = "no"

[week2]
pairs = [
    ["jacy", "jj"],
    ["jessica", "dillan"],
    ["paige", "chris"],
    ["simone", "scali"],
    ["shanley", "adam"],
    ["coleysia", "wes"],
    ["amber", "ethan"],
    ["brittany", "joey"],
    ["kayla", "ryan"],
    ["ashleigh", "dre"]
]
correct = 4
booth = ["ethan", "jessica"]
booth_status = "no"
